name: Deploy to gachon

on:
  push:
    branches:
      - gachonServer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          password : ${{secrets.password}}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: 22
          script: |
            ls -l
            cd ~/svr/v0.5/Bigdate
            git pull
            ./gradlew build
            PID=$( lsof -i :60003 | grep -v PID | awk '{print $2}')
            if [ -n "$PID" ]; then
              echo "Stopping the previous process (PID: $PID)..."
              kill -9 $PID
            fi
            fuser -k 60003/tcp
            cd build/libs
            nohup java -jar then-then-0.0.1-SNAPSHOT.jar > then-then.log 2>&1 &
